Set an upper bound for huggingface_hub version to resolve the ImportError of ModelFilter
ModelFilter has been deprecated in huggingface_hub 24.0 and later:

https://github.com/huggingface/huggingface_hub/releases/tag/v0.24.0

```
  File "/opt/NeMo/nemo/core/__init__.py", line 16, in <module>
    from nemo.core.classes import *
  File "/opt/NeMo/nemo/core/classes/__init__.py", line 20, in <module>
    from nemo.core.classes.common import (
  File "/opt/NeMo/nemo/core/classes/common.py", line 40, in <module>
    from nemo.core.classes.mixins.hf_io_mixin import HuggingFaceFileIO
  File "/opt/NeMo/nemo/core/classes/mixins/__init__.py", line 28, in <module>
    from nemo.core.classes.mixins.hf_io_mixin import HuggingFaceFileIO
  File "/opt/NeMo/nemo/core/classes/mixins/hf_io_mixin.py", line 19, in <module>
    from huggingface_hub import HfApi, ModelCard, ModelCardData, ModelFilter
ImportError: cannot import name 'ModelFilter' from 'huggingface_hub' (/usr/local/lib/python3.10/dist-packages/huggingface_hub/__init__.py)
```

Signed-off-by: Wei Ren <renwei2004@gmail.com>